import type { ComponentType } from "react";
import { FaLinkedin, FaGithub, FaInstagram } from "react-icons/fa";
import {
  BrainCircuit,
  Boxes,
  Building2,
  Cable,
  Cloud,
  Code2,
  Compass,
  Gauge,
  Globe,
  Layers,
  MessageCircle,
  Rocket,
  ScrollText,
  ShieldCheck,
  Smartphone,
  Sprout,
  TrendingUp,
  Workflow,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, ComponentType<{ className?: string }>> = {
  BrainCircuit,
  Boxes,
  Building2,
  Cable,
  Cloud,
  Code2,
  Compass,
  Gauge,
  Globe,
  Layers,
  MessageCircle,
  Rocket,
  ScrollText,
  ShieldCheck,
  Smartphone,
  Sprout,
  TrendingUp,
  Workflow,
  Zap,
  Linkedin: FaLinkedin,
  Github: FaGithub,
  Instagram: FaInstagram,
};
